### ISSUE TITLE
Highlighting Does No Work On Sublime Build 3143

### ISSUE THREAD

**Issue by justinlopez0** [SublimeText/TrailingSpaces#121] opened 2017-09-14 20:06 UTC
After updating Sublime, the plugin's highlighting feature no longer work.

**Comment by seppestas** [comment] 2017-09-22 12:47
Can confirm it stopped working (causing me to commit trailing spaces -.-).

Sublime text version 3.0 Build 3143, macOS version 10.12.6.

**Comment by anbotero** [comment] 2017-10-12 20:51
Confirmed.

I tried copy-pasting **all** the settings from Default configuration file into the user settings file, and the only line that changes with each plugin activation is the `trailing_spaces_highlight_color`. Like, you might have changed both `trailing_spaces_highlight_color` and `trailing_spaces_include_empty_lines` values in the user settings file, and if you activate the plugin (`super+alt+x` in my case), the user settings file will reload, and `trailing_spaces_highlight_color` is the only value that will be left empty.

**Comment by tcaddy** [comment] 2017-10-13 18:54
Confirmed.  on macOS, dev channel build 3148.

**Comment by Equim-chan** [comment] 2017-10-20 17:36
Comfirmed, on Windows 10, build 3143.
I checked console, it said the setting file was not found. Can that be the reason?
```
Traceback (most recent call last):
  File "D:\xxxx\Sublime Text Build 3143 x64\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\xxxx\Sublime Text Build 3143 x64\sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "trailing_spaces in D:\xxxx\Sublime Text Build 3143 x64\Data\Installed Packages\TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in D:\xxxx\Sublime Text Build 3143 x64\Data\Installed Packages\TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./python3.3/codecs.py", line 896, in open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\xxxx\\Sublime Text Build 3143 x64\\Data\\Packages\\TrailingSpaces\\trailing_spaces.sublime-settings'
```

**Comment by pensnarik** [comment] 2017-11-29 10:41
I have the same issue.`trailing_spaces_highlight_color` configuration parameter always reset to "" (empty string).

**Comment by pensnarik** [comment] 2017-11-29 11:30
I found that plugin reads empty string as default value from settings in `plugin_loaded()` function. So you can fix this issue just adding these lines before `DEFAULT_COLOR_SCOPE_NAME` declaration:
```python
    if current_highlighting_scope == '':
        current_highlighting_scope = "invalid"
```
I will try to find out the reason of this later. Maybe `sublime.load_settings()` method was changed in last Sublime build.

**Comment by becomesaflame** [comment] 2017-12-06 21:16
Windows 10, build 3143.
Clicking on Edit > Trailing Spaces > Highlight Regions has no effect.  A message appears in the bottom bar saying "Highlighting of Trailing Spaces is disabled!"  
Clicking the menu selection again has the same effect.
Nothing shows up in the console other than "reloading settings Packages/User/trailing_spaces.sublime-settings" when I click it.

**Comment by ecspresso** [comment] 2018-05-03 07:05
See issue #116. This fixes the problem, at least temporarily. Version 3.0 Build 3143.

> I had this problem all of a sudden, can't remember when it started, but I basically just had to enter a value and restart. See : https://stackoverflow.com/questions/16916060#answer-23051790
> 
> Sublime Text 3 Build 3143 default settings

**Comment by Pictor13** [comment] 2019-02-13 16:00
@ecspresso is right. Just tried now (set value _"invalid"_ and restart right after) and it works!

Although I have no time atm to see why that happens, fix the code and make a PR :(

**Comment by Nindaleth** [comment] 2019-02-14 12:32
Based on #125, for more recent Sublime Text 3 builds the "region.redish" might be a more fitting value than "invalid" for some color schemes.

**Comment by Pictor13** [comment] 2019-02-17 12:24
**Update:** to me the problem keeps reappearing regularly, even after fixing the settings.

The bug lays in persisting the setting in the code, assuming that the value is the one desired by the user, but looks like the settings are not loaded properly in some situations, so the plugin will find an empty string and re-persist that (why? 🤷‍♂️).

I think there should be a specific setting value that should be intended to disable trailing spaces.
Using an empty string as "disable" setting leads to this weird behaviour.
If not wanting to use a specific value then the logic in the code should be fixed.

**Comment by rchl** [comment] 2020-03-23 19:24
Duplicate of #65

**Closed by rchl** 2020-03-23 19:24 UTC
