### ISSUE TITLE
Does not highlight anything in Sublime 3, even after setting trailing_spaces_highlight_color

### ISSUE THREAD

**Issue by aminariana** [SublimeText/TrailingSpaces#116] opened 2017-05-02 21:49 UTC
Repro:
1. Install via package installer on Sublime 3 with MacOS Classic theme
2. Set `trailing_spaces_highlight_color` to one of `invalid`, `error` or `comment`

Expected:
Highlighted trailing spaces

Actual:
Not highlighted ever, with or without the setting. (Delete does work)

**Comment by stav** [comment] 2017-08-14 18:40
I had this problem all of a sudden, can't remember when it started, but I basically just had to enter a value and restart. See : https://stackoverflow.com/questions/16916060#answer-23051790

**Comment by webdevnerdstuff** [comment] 2017-10-10 16:37
I'm also having this problem with Build 3148. Nothing changes the color, including adding custom color scope.

**Comment by Pictor13** [comment] 2019-02-17 13:47
Because of how the code is written you need to save the setting file and close Sublime, before it works.

**Comment by rchl** [comment] 2020-03-23 19:23
Duplicate of #65

**Closed** 2020-03-28 11:45 UTC
